// This file was autogenerated by calcdeps.js
goog.addDependency("../../src/antialiasing.js", ["tr.Antialiasing"], ["tr.Platform","tr.Browser","tr.Version"]);
goog.addDependency("../../src/browser.js", ["tr.Browser"], []);
goog.addDependency("../../src/dom.js", ["tr.dom"], []);
goog.addDependency("../../src/platform.js", ["tr.Platform"], []);
goog.addDependency("../../src/rasterizer.js", ["tr.Rasterizer"], ["tr.Platform","tr.Browser","tr.Version"]);
goog.addDependency("../../src/tr.js", ["tr"], ["tr.UserAgent","tr.Rasterizer","tr.Antialiasing","tr.dom"]);
goog.addDependency("../../src/useragent.js", ["tr.UserAgent"], ["tr.Browser","tr.Platform","tr.Version"]);
goog.addDependency("../../src/version.js", ["tr.Version"], []);
